import { NextPage } from "next";
import Head from "next/head";
import Home from "../components/Home";
import Script from "next/script"
const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Maykel Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://app.embed.im/snow.js" defer></Script>

      <Home />
    </>
  );
};
export default HomePage;
