import { NextPage } from "next";
import Head from "next/head";
import Home from "../components/Home";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Maykel Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://app.embed.im/snow.js" defer></script>
      </Head>
      <Home />
    </>
  );
};
export default HomePage;
